### ISSUE TITLE
Simply running babyai example after installation (Ubuntu 20.04)

### ISSUE THREAD

**Issue by mattdeitke** [allenai/allenact#214]
## Problem

After installing AllenAct with either pip or pipenv, simply running the basic babyai experiment
```
python main.py minigrid_tutorial -b projects/tutorials -m 8 -o minigrid_output -s 12345
```

fails with the following output details:

<details>

```
10/08 11:23:49 INFO: Running with args Namespace(checkpoint=None, deterministic_agents=False, deterministic_cudnn=False, experiment='minigrid_tutorial', experiment_base='projects/tutorials', extra_tag='', gp=None, log_level='info', max_sampler_processes_per_worker=8, output_dir='minigrid_output', restart_pipeline=False, seed=12345, skip_checkpoints=0, test_date=None)     [main.py: 242]
10/08 11:23:49 ERROR: Uncaught exception:       [system.py: 137]
Traceback (most recent call last):
  File "main.py", line 205, in load_config
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./projects/tutorials/minigrid_tutorial.py", line 12, in <module>
    from plugins.minigrid_plugin.minigrid_sensors import EgocentricMiniGridSensor
  File "./plugins/minigrid_plugin/minigrid_sensors.py", line 8, in <module>
    from babyai.utils.format import InstructionsPreprocessor
ModuleNotFoundError: No module named 'babyai'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "main.py", line 282, in <module>
    main()
  File "main.py", line 246, in main
    cfg, srcs = load_config(args)
  File "main.py", line 219, in load_config
    ) from e
ModuleNotFoundError: Could not import experiment 'projects.tutorials.minigrid_tutorial', are you sure this is the right path? Possibly relevant files include ['./allenact/projects/tutorials/minigrid_tutorial.py'].
```

</details>

## Desktop

Please add the following information:
 - OS: Ubuntu 20.04
 - AllenAct Version: current HEAD of master

## Additional context

Perhaps it's a paths issue, but I'm not sure of an immediate fix.

Matt :)

**Comment by mattdeitke** [comment]
It seems that babyai's installation failed silently for me with `pip install -r requirements.txt`. Reinstalling it afterward by manually running:
```
pip install -e git+https://github.com/unnat/babyai.git@ff645fe00ea8412a29bd5e2d6f79ae1595d229a7#egg=babyai
```
worked!
