### ISSUE TITLE
AttributeError: 'RolloutBlockStorage' object has no attribute 'memory'

### ISSUE THREAD

**Issue by ShoufaChen** [allenai/allenact#365]
## Problem

```
[05/08 20:01:01 ERROR:] Traceback (most recent call last):
  File "/home/chenshoufa/workspace/allenact/allenact/algorithms/onpolicy_sync/engine.py", line 1992, in process_checkpoints
    eval_package = self.run_eval(
  File "/home/chenshoufa/workspace/allenact/allenact/algorithms/onpolicy_sync/engine.py", line 1830, in run_eval
    self.collect_step_across_all_task_samplers(
  File "/home/chenshoufa/workspace/allenact/allenact/algorithms/onpolicy_sync/engine.py", line 664, in collect_step_across_all_task_samplers
    visualizer.collect(
  File "/home/chenshoufa/workspace/allenact/allenact/utils/viz_utils.py", line 996, in collect
    self._collect_rollout(rollout=rollout, alive=alive)
  File "/home/chenshoufa/workspace/allenact/allenact/utils/viz_utils.py", line 887, in _collect_rollout
    res = getattr(rollout, storage)
AttributeError: 'RolloutBlockStorage' object has no attribute 'memory'
```

## Steps to reproduce

https://allenact.org/tutorials/running-inference-on-a-pretrained-model/#visualization

```
PYTHONPATH=. python allenact/main.py \
running_inference_tutorial \
-o pretrained_model_ckpts/robothor-pointnav-rgb-resnet/ \
-b projects/tutorials \
-c pretrained_model_ckpts/robothor-pointnav-rgb-resnet/checkpoints/PointNavRobothorRGBPPO/2020-08-31_12-13-30/exp_PointNavRobothorRGBPPO__stage_00__steps_000039031200.pt \
--eval
```

**Comment by Lucaweihs** [comment]
Hi @ShoufaChen, thanks for the bug report, this should now be fixed on the `main` branch, please reopen if it still doesn't work for you.
