### ISSUE TITLE
Displayconnection error

### ISSUE THREAD

**Issue by rginjapan** [allenai/allenact#379]
## Problem / Question
I would like to run allenact on display mode, i got the following error:

> [04/18 15:51:40 ERROR:] [test worker 0] Encountered DisplayConnectionError, exiting.    [engine.py: 1904]

**Comment by jordis-ai2** [comment]
Hi @rginjapan,

I think it would be best for us to provide assistance if you could describe the platform you're using, including, if using linux, the graphics driver and version, and also the script you're trying to run.

Thank you.

**Comment by Aliiiranmanesh** [comment]
I have a headless workstation and I did all the given steps in readme (the startx script and changing ID and addding the line for headless=true) but I still get this error"PYTHONPATH=. python allenact/main.py -o storage/embclip-zeroshot -c $CKPT_PATH -b projects/objectnav_baselines/experiments/robothor/clip zeroshot_objectnav_robothor_rgb_clipresnet50gru_ddppo_eval --eval
[05/21 20:22:13 INFO:] Running with args Namespace(approx_ckpt_step_interval=None, approx_ckpt_steps_count=None, checkpoint='/home/afi5220/embclip-zeroshot/pretrained_model_ckpts/exp_Zeroshot-ObjectNav-RoboTHOR-RGB-ClipResNet50GRU-DDPPO__stage_00__steps_000055057640.pt', collect_valid_results=False, config_kwargs=None, deterministic_agents=False, deterministic_cudnn=False, disable_config_saving=False, disable_tensorboard=False, distributed_ip_and_port='127.0.0.1:0', eval=True, experiment='zeroshot_objectnav_robothor_rgb_clipresnet50gru_ddppo_eval', experiment_base='projects/objectnav_baselines/experiments/robothor/clip', extra_tag='', infer_output_dir=False, log_level='info', machine_id=0, max_sampler_processes_per_worker=None, output_dir='storage/embclip-zeroshot', restart_pipeline=False, save_dir_fmt=<SaveDirFormat.FLAT: 'FLAT'>, seed=None, skip_checkpoints=0, test_date=None, test_expert=False)	[main.py: 420]
[05/21 20:22:14 INFO:] Using 1 test workers on devices (device(type='cuda', index=0),)	[runner.py: 239]
[05/21 20:22:16 INFO:] Started 1 test processes	[runner.py: 596]
[05/21 20:22:16 INFO:] Running test on 1 steps [55057640]	[runner.py: 606]
[05/21 20:22:16 INFO:] test 0 args {'config': <projects.objectnav_baselines.experiments.robothor.clip.zeroshot_objectnav_robothor_rgb_clipresnet50gru_ddppo_eval.EvalZeroshotObjectNavRoboThorClipRGBPPOExperimentConfig object at 0x70d9f9e4ed30>, 'results_queue': <multiprocessing.queues.Queue object at 0x70d9e5b0c2e0>, 'checkpoints_queue': <multiprocessing.queues.Queue object at 0x70d9e5b281f0>, 'seed': 12345, 'deterministic_cudnn': False, 'deterministic_agents': False, 'mp_ctx': <multiprocessing.context.ForkServerContext object at 0x70d9e5b28a30>, 'num_workers': 1, 'device': device(type='cuda', index=0), 'max_sampler_processes_per_worker': None, 'distributed_port': 0, 'enforce_expert': False, 'mode': 'test', 'worker_id': 0}	[runner.py: 356]
[05/21 20:22:16 INFO:] Saving test metrics in storage/embclip-zeroshot/metrics/Zeroshot-ObjectNav-RoboTHOR-RGB-ClipResNet50GRU-DDPPO/2025-05-21_20-22-14/metrics__test_2025-05-21_20-22-14.json	[runner.py: 629]
[05/21 20:22:16 INFO:] Using checkpoint start time pretrained_model_ckpts	[runner.py: 647]
[05/21 20:22:19 INFO:] there are 1 belief models: ['single_belief']	[visual_nav_models.py: 114]
[05/21 20:22:19 INFO:] [test worker 0] Loading checkpoint from /home/afi5220/embclip-zeroshot/pretrained_model_ckpts/exp_Zeroshot-ObjectNav-RoboTHOR-RGB-ClipResNet50GRU-DDPPO__stage_00__steps_000055057640.pt	[engine.py: 364]
[05/21 20:22:19 WARNING:] `test_on_validation` is set to `True` and thus we will run evaluation on the validation set instead. Be careful as the saved metrics json and tensorboard files **will still be labeled as 'test' rather than 'valid'**.	[objectnav_thor_base.py: 331]
[05/21 20:22:19 ERROR:] [test worker 0] Encountered DisplayConnectionError, exiting.	[engine.py: 1904]
[05/21 20:22:19 ERROR:] Traceback (most recent call last):
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/engine.py", line 1875, in process_checkpoints
    eval_package = self.run_eval(
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/engine.py", line 1669, in run_eval
    num_paused = self.initialize_storage_and_viz(
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/engine.py", line 439, in initialize_storage_and_viz
    observations = self.vector_tasks.get_observations()
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/engine.py", line 297, in vector_tasks
    sampler_fn_args=self.get_sampler_fn_args(seeds),
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/engine.py", line 350, in get_sampler_fn_args
    return [
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/engine.py", line 351, in <listcomp>
    fn(
  File "/home/afi5220/embclip-zeroshot/projects/objectnav_baselines/experiments/objectnav_thor_base.py", line 343, in test_task_sampler_args
    return self.valid_task_sampler_args(
  File "/home/afi5220/embclip-zeroshot/projects/objectnav_baselines/experiments/objectnav_thor_base.py", line 306, in valid_task_sampler_args
    res = self._get_sampler_args_for_scene_split(
  File "/home/afi5220/embclip-zeroshot/projects/objectnav_baselines/experiments/objectnav_thor_base.py", line 238, in _get_sampler_args_for_scene_split
    x_displays = get_open_x_displays(throw_error_if_empty=True)
  File "/home/afi5220/embclip-zeroshot/allenact_plugins/ithor_plugin/ithor_util.py", line 76, in get_open_x_displays
    display = Xlib.display.Display(":{}".format(open_display_str))
  File "/home/afi5220/anaconda3/envs/embclip-zeroshot/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/afi5220/anaconda3/envs/embclip-zeroshot/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/afi5220/anaconda3/envs/embclip-zeroshot/lib/python3.8/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
	[engine.py: 1907]
[05/21 20:22:19 ERROR:] Encountered Exception. Terminating runner.	[runner.py: 1251]
[05/21 20:22:19 ERROR:] Traceback (most recent call last):
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/runner.py", line 1235, in log_and_close
    raise RuntimeError(
RuntimeError: Test worker 0 abnormally terminated
	[runner.py: 1252]
Traceback (most recent call last):
  File "/home/afi5220/embclip-zeroshot/allenact/algorithms/onpolicy_sync/runner.py", line 1235, in log_and_close
    raise RuntimeError(
RuntimeError: Test worker 0 abnormally terminated
[05/21 20:22:19 INFO:] Terminating test 0	[runner.py: 1327]
[05/21 20:22:19 INFO:] Joining test 0	[runner.py: 1327]
[05/21 20:22:19 INFO:] Closed test 0	[runner.py: 1327]"
